/**
 * server/orchestrator/mcp/read.ts
 *
 * Orchestrator MCP **read** tool handlers (Task 1.5 / SHR-121).
 *
 * These are thin wrappers over existing octomux DB functions that return
 * **lean summaries and pointers only** — never full row dumps, file bodies,
 * or diff contents. The orchestrator must hold pointers, not contents (§1, §8).
 *
 * Tools:
 *   monitor_status   — cross-task rollup: counts + needs_attention list
 *   get_task_output  — artifact pointers from managed_tasks.artifacts JSON
 *   search_learnings — shared-lane agent_learnings recall (lean rows only)
 *
 * `list_tasks` / `get_task` used to live here (lean-only handlers) but are now
 * generated by the capability registry (`server/registry/capabilities/task.ts`,
 * `task.list` / `task.get`) — that capability defaults to the SAME lean shape
 * these handlers used to return, with a `include=` opt-in for the full task
 * row + relations, so there's exactly one implementation of "get/list a task"
 * shared by the dashboard, the CLI, and MCP. See `server/orchestrator/mcp/server.ts`'s
 * module doc for how it's wired in.
 *
 * These handlers are called both by the MCP server (server.ts) and by tests
 * directly so they are exported as plain functions (no transport coupling).
 */

import { promisify } from 'util';
import { execFile as execFileCb } from 'child_process';
import { execTmux } from '../../tmux-bin.js';
import {
  getTask,
  listTasks,
  countTasks,
  countAgentsForTask,
  listAgentsByTasks,
  listPendingPromptsByTasks,
  listRecentRepoPaths,
} from '../../repositories/index.js';
import { recallLearnings } from '../../routes/learnings.js';
import { listSchedules } from '../../repositories/schedules.js';
import { listPresets } from '../../workflows/presets.js';
import { getSettings } from '../../settings.js';
import {
  getManagedTask,
  countManagedTasksByPhase,
  eventsSince,
} from '../../repositories/orchestrator.js';
import { childLogger } from '../../logger.js';
import type { Task } from '../../types.js';

const execFile = promisify(execFileCb);

const logger = childLogger('orchestrator/mcp/read');

// ─── Input types ──────────────────────────────────────────────────────────────

export type MonitorStatusInput = Record<string, never>;

export interface GetTaskOutputInput {
  task_id: string;
}

// ─── Output types ─────────────────────────────────────────────────────────────

export interface MonitorStatusResult {
  total: number;
  by_runtime_state: Record<string, number>;
  by_workflow_status: Record<string, number>;
  /**
   * Counts by managed phase from managed_tasks (planning / awaiting_approval /
   * implementing / reviewing / done). Only present for orchestrator-managed tasks.
   */
  by_phase: Record<string, number>;
  /** Tasks in error state or awaiting attention (id + title only). */
  needs_attention: Array<{ id: string; title: string; reason: string }>;
}

/** Artifact pointers only. Contents are never returned. */
export interface TaskOutputPointers {
  /** Path to the plan artifact in the task's worktree (e.g. 'plan.json'). */
  plan?: string;
  /** URL to the diff view in the octomux dashboard. */
  diff_url?: string;
  /** Test run status as a short string (e.g. 'passing', 'failing'). */
  tests?: string;
}

// ─── monitor_status ───────────────────────────────────────────────────────────

/**
 * Cross-task rollup: counts by runtime_state and workflow_status, plus a
 * needs_attention list for tasks that require human action (error, or tasks
 * with pending permission prompts).
 *
 * Returns summaries only — never full task rows.
 */
export function handleMonitorStatus(_input: MonitorStatusInput): MonitorStatusResult {
  logger.debug({ operation: 'monitor_status' }, 'monitor_status called');

  // Total active (non-deleted) tasks
  const total = countTasks();

  // All non-deleted tasks for rollup computation. Must match countTasks()'s scope — it counts
  // every task, so excluding automated sources here would desync `total` from the breakdown.
  const allTasks = listTasks({ includeAutoReview: true, includeAutomated: true });
  const taskIds = allTasks.map((t) => t.id);
  const taskMap = new Map<string, Task>(allTasks.map((t) => [t.id, t]));

  // Counts by runtime_state (JS groupBy)
  const by_runtime_state: Record<string, number> = {};
  for (const t of allTasks) {
    by_runtime_state[t.runtime_state] = (by_runtime_state[t.runtime_state] ?? 0) + 1;
  }

  // Counts by workflow_status (JS groupBy)
  const by_workflow_status: Record<string, number> = {};
  for (const t of allTasks) {
    by_workflow_status[t.workflow_status] = (by_workflow_status[t.workflow_status] ?? 0) + 1;
  }

  // Counts by managed phase across ALL managed_tasks rows (incl. soft-deleted
  // tasks), matching the original ungated GROUP BY.
  const by_phase = countManagedTasksByPhase();

  // Awaiting-approval set: only live (non-deleted) tasks, with their titles.
  const awaitingApprovalTasks: Array<{ id: string; title: string }> = [];
  for (const t of allTasks) {
    const mt = getManagedTask(t.id);
    if (mt && mt.phase === 'awaiting_approval') {
      awaitingApprovalTasks.push({ id: t.id, title: t.title });
    }
  }

  // Needs-attention: error tasks (filter from allTasks)
  const errorTasks = allTasks
    .filter((t) => t.runtime_state === 'error')
    .map((t) => ({ id: t.id, title: t.title }));

  // Needs-attention: tasks with pending permission prompts
  const pendingPrompts = listPendingPromptsByTasks(taskIds);
  const pendingPromptTaskIdSet = new Set(pendingPrompts.map((p) => p.task_id));
  const pendingPromptTasks = [...pendingPromptTaskIdSet]
    .map((id) => taskMap.get(id))
    .filter((t): t is Task => t !== undefined)
    .map((t) => ({ id: t.id, title: t.title }));

  // Needs-attention: tasks whose agents have hook_activity='waiting'
  const allAgents = listAgentsByTasks(taskIds);
  const hookWaitingTaskIdSet = new Set(
    allAgents
      .filter((a) => a.hook_activity === 'waiting' && a.task_id !== null)
      .map((a) => a.task_id as string),
  );
  const hookWaitingTasks = [...hookWaitingTaskIdSet]
    .map((id) => taskMap.get(id))
    .filter((t): t is Task => t !== undefined)
    .map((t) => ({ id: t.id, title: t.title }));

  // Needs-attention: tasks with task:stuck events (eventsSince(0) = all events)
  const allEvents = eventsSince(0);
  const stuckTaskIdSet = new Set(
    allEvents.filter((e) => e.type === 'task:stuck').map((e) => e.task_id),
  );
  const stuckTasks = [...stuckTaskIdSet]
    .filter((id) => taskMap.has(id))
    .map((id) => taskMap.get(id)!)
    .map((t) => ({ id: t.id, title: t.title }));

  const needs_attention: MonitorStatusResult['needs_attention'] = [
    ...errorTasks.map((t) => ({ id: t.id, title: t.title, reason: 'error' })),
    ...pendingPromptTasks.map((t) => ({ id: t.id, title: t.title, reason: 'pending_prompt' })),
    ...awaitingApprovalTasks.map((t) => ({
      id: t.id,
      title: t.title,
      reason: 'awaiting_approval',
    })),
    ...hookWaitingTasks.map((t) => ({ id: t.id, title: t.title, reason: 'hook_waiting' })),
    ...stuckTasks.map((t) => ({ id: t.id, title: t.title, reason: 'stuck' })),
  ];

  // Deduplicate by id (first reason wins — priority order: error > pending_prompt > awaiting_approval > hook_waiting > stuck)
  const seen = new Set<string>();
  const deduped = needs_attention.filter((t) => {
    if (seen.has(t.id)) return false;
    seen.add(t.id);
    return true;
  });

  return {
    total,
    by_runtime_state,
    by_workflow_status,
    by_phase,
    needs_attention: deduped,
  };
}

// ─── get_task_output ──────────────────────────────────────────────────────────

/**
 * Return artifact pointers for a task from its managed_tasks.artifacts JSON.
 *
 * CRITICAL: this tool returns POINTERS ONLY — never file contents, never diff
 * bodies. The orchestrator may hold the path and diff_url; contents are fetched
 * browser-side by the UI via GET /api/orchestrator/artifact.
 *
 * Returns an empty object if the task has no managed_tasks row yet.
 */
export function handleGetTaskOutput(input: GetTaskOutputInput): TaskOutputPointers {
  const { task_id } = input;

  logger.debug({ operation: 'get_task_output', task_id }, 'get_task_output called');

  const mt = getManagedTask(task_id);
  if (!mt || !mt.artifacts) {
    return {};
  }

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(mt.artifacts) as Record<string, unknown>;
  } catch {
    logger.warn({ task_id, artifacts: mt.artifacts }, 'get_task_output: invalid artifacts JSON');
    return {};
  }

  const pointers: TaskOutputPointers = {};

  if (typeof parsed.plan === 'string') {
    pointers.plan = parsed.plan;
  }
  if (typeof parsed.diff_url === 'string') {
    pointers.diff_url = parsed.diff_url;
  }
  if (typeof parsed.tests === 'string') {
    pointers.tests = parsed.tests;
  }

  return pointers;
}

// ─── get_agent_output ─────────────────────────────────────────────────────────

export interface GetAgentOutputInput {
  task_id: string;
}

export interface AgentOutputResult {
  /** Whether a live agent tmux session exists (false = stopped / not started). */
  live: boolean;
  /** Number of agents on the task. */
  agent_count: number;
  /** The tail of the agent's live terminal — its actual recent output. */
  output: string;
  /** Human note when there's nothing to read. */
  note?: string;
}

/** Lines of the agent pane to return. */
const AGENT_OUTPUT_LINES = 40;
/** Cap the returned text so the conductor holds a tail, not a dump. */
const AGENT_OUTPUT_MAX_CHARS = 4000;

/**
 * Return the tail of an agent's LIVE terminal — the one thing the status/pointer
 * tools can't give: what the agent is actually doing/saying right now. Reads the
 * task's tmux session via `capture-pane` (the same content the dashboard shows).
 *
 * Returns `live: false` with a note when the session is gone (agent stopped) —
 * which, paired with `get_task`'s `phase`, lets the conductor tell "finished" and
 * "paused at a gate" apart from "actively working" instead of guessing from
 * `runtime_state`.
 */
export async function handleGetAgentOutput(input: GetAgentOutputInput): Promise<AgentOutputResult> {
  const { task_id } = input;
  logger.debug({ operation: 'get_agent_output', task_id }, 'get_agent_output called');

  const task = getTask(task_id);
  if (!task || task.deleted_at) {
    return { live: false, agent_count: 0, output: '', note: 'task not found' };
  }

  const agent_count = countAgentsForTask(task_id);
  const session = task.tmux_session ?? `octomux-agent-${task_id}`;

  try {
    await execTmux(['has-session', '-t', session]);
  } catch {
    return {
      live: false,
      agent_count,
      output: '',
      note: 'no live agent session — the agent has stopped or has not started',
    };
  }

  try {
    const { stdout } = await execTmux(['capture-pane', '-t', session, '-p']);
    const lines = stdout.split('\n').filter((l) => l.trim());
    let output = lines.slice(-AGENT_OUTPUT_LINES).join('\n');
    if (output.length > AGENT_OUTPUT_MAX_CHARS) {
      output = output.slice(output.length - AGENT_OUTPUT_MAX_CHARS);
    }
    return { live: true, agent_count, output };
  } catch (err) {
    logger.warn({ task_id, session, err }, 'get_agent_output: capture-pane failed');
    return { live: false, agent_count, output: '', note: 'failed to read agent terminal' };
  }
}

// ─── recent_repos ─────────────────────────────────────────────────────────────

export interface RecentRepoRow {
  repo_path: string;
  last_used: string;
}

/**
 * Return the 10 most-recently-used distinct repo paths from past tasks.
 * Never returns deleted tasks' repos.
 */
export function handleRecentRepos(): RecentRepoRow[] {
  logger.debug({ operation: 'recent_repos' }, 'recent_repos called');

  return listRecentRepoPaths(10) as RecentRepoRow[];
}

// ─── default_branch ───────────────────────────────────────────────────────────

export interface DefaultBranchInput {
  repo_path: string;
}

export interface DefaultBranchResult {
  branch: string;
}

/**
 * Return the default branch of a git repo by inspecting refs/remotes/origin/HEAD.
 * Falls back to 'main' on any error (missing remote, not a git repo, etc.).
 */
export async function handleDefaultBranch(input: DefaultBranchInput): Promise<DefaultBranchResult> {
  const { repo_path } = input;

  logger.debug({ operation: 'default_branch', repo_path }, 'default_branch called');

  try {
    const { stdout } = await execFile('git', [
      '-C',
      repo_path,
      'symbolic-ref',
      'refs/remotes/origin/HEAD',
    ]);
    const branch = stdout.trim().replace('refs/remotes/origin/', '');
    return { branch };
  } catch {
    logger.debug({ operation: 'default_branch', repo_path }, 'default_branch fallback to main');
    return { branch: 'main' };
  }
}

// ─── list_schedules ───────────────────────────────────────────────────────────

/** Lean schedule row — omits config_json and the (potentially long) prompt body. */
export interface ScheduleSummary {
  id: string;
  kind: string;
  name: string | null;
  repo_path: string;
  cron: string;
  timezone: string | null;
  enabled: boolean;
  model: string | null;
  last_run_at: string | null;
}

/** List all cron schedules as lean summaries (advisor read tool). */
export function handleListSchedules(): ScheduleSummary[] {
  logger.debug({ operation: 'list_schedules' }, 'list_schedules called');
  return listSchedules().map((r) => ({
    id: r.id,
    kind: r.kind,
    name: r.name ?? null,
    repo_path: r.repo_path,
    cron: r.cron,
    timezone: r.timezone ?? null,
    enabled: !!r.enabled,
    model: r.model ?? null,
    last_run_at: r.last_run_at ?? null,
  }));
}

// ─── list_schedule_kinds ──────────────────────────────────────────────────────

export interface ScheduleKindSummary {
  kind: string;
  displayName: string;
  execution: string;
  defaultCron: string | null;
  /** true = the kind ships no preset prompt; create_schedule must supply one. */
  promptRequired: boolean;
}

/** List the schedule kinds (presets) available for create_schedule. */
export function handleListScheduleKinds(): ScheduleKindSummary[] {
  logger.debug({ operation: 'list_schedule_kinds' }, 'list_schedule_kinds called');
  return listPresets().map((p) => ({
    kind: p.kind,
    displayName: p.displayName,
    execution: p.execution,
    defaultCron: p.defaultCron ?? null,
    promptRequired: !p.prompt,
  }));
}

// ─── get_settings ─────────────────────────────────────────────────────────────

/**
 * Curated settings summary. Deliberately EXCLUDES the `compute` blobs (their
 * `secrets` sub-objects must never reach an agent) and harness/plugin config
 * values — only the ids are listed.
 */
export interface SettingsSummary {
  editor: string;
  defaultHarnessId: string;
  defaultComputeKind: string;
  configuredHarnessIds: string[];
  configuredComputeKinds: string[];
  configuredPluginIds: string[];
  defaultTracker: string | null;
  defaultBaseBranch: string | null;
  aiTaskNaming: boolean;
  fanoutMaxConcurrency: number | null;
}

export async function handleGetSettings(): Promise<SettingsSummary> {
  logger.debug({ operation: 'get_settings' }, 'get_settings called');
  const s = await getSettings();
  return {
    editor: s.editor,
    defaultHarnessId: s.defaultHarnessId,
    defaultComputeKind: s.defaultComputeKind,
    configuredHarnessIds: Object.keys(s.harnesses),
    configuredComputeKinds: Object.keys(s.compute),
    configuredPluginIds: Object.keys(s.plugins),
    defaultTracker: s.defaultTracker ?? null,
    defaultBaseBranch: s.defaultBaseBranch ?? null,
    aiTaskNaming: s.aiTaskNaming ?? false,
    fanoutMaxConcurrency: s.fanout?.maxConcurrency ?? null,
  };
}

// ─── search_learnings ─────────────────────────────────────────────────────────

export interface SearchLearningsInput {
  query: string;
  repo?: string;
}

/** Lean learning row — pointers only, never the full agent_learnings row. */
export interface LearningSummary {
  trigger: string;
  lesson: string;
  evidence: string | null;
  repo_path: string;
}

/**
 * Search the shared-lane agent_learnings store for a recall query (spec §12
 * agent-learnings; gateway Task 2). Cross-repo unless `repo` is given.
 * Returns lean summaries only — never the full row (usage_count, ids, etc.).
 *
 * Delegates to `recallLearnings` (server/routes/learnings.ts) — the same
 * in-process function `GET /api/learnings` calls — with no `taskId` (this
 * tool runs on the conductor's MCP server, which has no per-task context, so
 * this preserves the shared-lane-only / no-usage-bump behaviour this tool
 * always had). One implementation of "recall a learning" now, not two.
 */
export function handleSearchLearnings(input: SearchLearningsInput): LearningSummary[] {
  const { query, repo } = input;

  logger.debug({ operation: 'search_learnings', query, repo }, 'search_learnings called');

  const rows = recallLearnings({ query, repo });

  return rows.map((r) => ({
    trigger: r.trigger,
    lesson: r.lesson,
    evidence: r.evidence,
    repo_path: r.repo_path,
  }));
}
