/**
 * server/orchestrator/mcp/server.ts
 *
 * Octomux orchestrator MCP server (Task 1.5 / SHR-121; seed SHR-135).
 *
 * Exposes typed READ tools to the conductor `claude` session:
 *   monitor_status     — cross-task rollup + needs_attention list
 *   get_task_output    — artifact pointers from managed_tasks (plan/diff_url/tests)
 *   get_agent_output   — tail of an agent's live terminal
 *   pull_linear_issue  — lean Linear issue summary (pointer to ticket; seed §12 Phase 4)
 *   search_learnings   — shared-lane agent_learnings recall (lean rows; gateway Task 2)
 *
 * `list_tasks` / `get_task` / `create_task` / `set_task_status` / `close_task` /
 * `delete_task` are generated instead, from the capability registry
 * (`server/registry/capabilities/task.ts` via `registerCapabilityMcpTools()`) —
 * see the call site below for the caller-class + env-gating rationale. This
 * supersedes the hand-written `list_tasks`/`get_task` read tools that used to
 * live here, and the `create_task`/`set_task_status`/`close_task`/`delete_task`
 * entries of the COMMANDS write loop below (those entries stay in
 * `command-registry.ts` — still needed for the Bash-gated `octomux` CLI path,
 * which this file doesn't touch).
 *
 * All other tools here are **read-only**. Write actions go through the Bash
 * tool + PreToolUse gate (§5 of the spec) for worker sessions, or the COMMANDS
 * write loop below for the conductor. The server runs over stdio so it can be
 * launched as an `--mcp-config` server by the orchestrator process.
 *
 * Usage (launched by the harness via --mcp-config):
 *   node dist-server/orchestrator/mcp/server.js
 */

import { fileURLToPath } from 'url';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { childLogger } from '../../logger.js';
import {
  handleMonitorStatus,
  handleGetTaskOutput,
  handleGetAgentOutput,
  handleRecentRepos,
  handleDefaultBranch,
  handleSearchLearnings,
} from './read.js';
import { handlePullLinearIssue } from './seed.js';
import {
  callOrchestratorAction,
  callPhaseComplete,
  orchestratorWriteEnabled,
  workerReportEnabled,
} from './write.js';
import { COMMANDS } from '../command-registry.js';
import { registerCapabilityMcpTools } from '../../registry/mount.js';

/**
 * MCP tool names now generated by the capability registry
 * (`task.create`/`task.move`/`task.close`/`task.delete` — see
 * `server/registry/capabilities/task.ts`). Excluded from the COMMANDS write
 * loop below so the MCP SDK never sees the same tool name registered twice.
 */
const CAPABILITY_MCP_NAMES = new Set([
  'create_task',
  'set_task_status',
  'close_task',
  'delete_task',
]);

const logger = childLogger('orchestrator/mcp/server');

// ─── Server factory ───────────────────────────────────────────────────────────

/**
 * Create and configure the octomux MCP server with all read tools.
 * Returns the McpServer instance (not yet connected to a transport).
 */
export function createOctomuxMcpServer(): McpServer {
  const server = new McpServer(
    { name: 'octomux', version: '1.0.0' },
    { capabilities: { tools: {} } },
  );

  // list_tasks / get_task are registered below via registerCapabilityMcpTools,
  // unconditionally — they are 'auto' tier, so both the conductor and a worker
  // get them. See the module doc and the call site further down.

  // ── monitor_status ──────────────────────────────────────────────────────────
  server.registerTool(
    'monitor_status',
    {
      description:
        'Get a cross-task rollup: total task count, counts by runtime_state and workflow_status, ' +
        'and a needs_attention list (tasks in error state or with pending permission prompts). ' +
        'Never returns full task rows — only id, title, and reason.',
      inputSchema: {},
    },
    (_args) => {
      logger.debug({ operation: 'monitor_status' }, 'MCP monitor_status invoked');
      const status = handleMonitorStatus({});
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(status, null, 2),
          },
        ],
      };
    },
  );

  // ── get_task_output ─────────────────────────────────────────────────────────
  server.registerTool(
    'get_task_output',
    {
      description:
        'Get artifact pointers for a managed task. ' +
        'Returns {plan?, diff_url?, tests?} — file paths and URLs only, NEVER file contents. ' +
        'The UI fetches contents via GET /api/orchestrator/artifact; the orchestrator holds the pointer.',
      inputSchema: {
        task_id: z.string().describe('The octomux task id'),
      },
    },
    (args) => {
      logger.debug(
        { operation: 'get_task_output', task_id: args.task_id },
        'MCP get_task_output invoked',
      );
      const pointers = handleGetTaskOutput(args);
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(pointers, null, 2),
          },
        ],
      };
    },
  );

  // ── get_agent_output ──────────────────────────────────────────────────────────
  server.registerTool(
    'get_agent_output',
    {
      description:
        "Read the TAIL of an agent's live terminal for a task — what the agent is " +
        'actually doing/saying right now (the same view as the dashboard terminal). ' +
        "Use this when you need the agent's recent output/last message, which get_task " +
        'and get_task_output do NOT provide (they return status + artifact pointers only). ' +
        'Returns {live, agent_count, output, note?}; live:false means the agent has stopped.',
      inputSchema: {
        task_id: z.string().describe('The octomux task id'),
      },
    },
    async (args) => {
      logger.debug(
        { operation: 'get_agent_output', task_id: args.task_id },
        'MCP get_agent_output invoked',
      );
      const result = await handleGetAgentOutput(args);
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    },
  );

  // ── pull_linear_issue ───────────────────────────────────────────────────────
  server.registerTool(
    'pull_linear_issue',
    {
      description:
        'Fetch a Linear issue and return a lean summary (pointer to the ticket). ' +
        'Returns {id, identifier, title, url, state?, priority?, estimate?, labels?, team_key?, description_snippet?}. ' +
        'The url is the authoritative pointer to the full ticket. ' +
        'description_snippet is ≤256 chars — NEVER the full body. ' +
        'Use to seed a planning session with issue context (spec §12 Phase 4).',
      inputSchema: {
        issue_id: z.string().describe("Linear issue identifier (e.g. 'SHR-123') or UUID"),
        api_key: z.string().describe('Linear API key (bare, no Bearer prefix)'),
      },
    },
    async (args) => {
      logger.debug(
        { operation: 'pull_linear_issue', issue_id: args.issue_id },
        'MCP pull_linear_issue invoked',
      );
      const summary = await handlePullLinearIssue(args);
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(summary, null, 2),
          },
        ],
      };
    },
  );

  // ── recent_repos ────────────────────────────────────────────────────────────
  server.registerTool(
    'recent_repos',
    {
      description:
        'List the 10 most-recently-used distinct git repo paths from past octomux tasks. ' +
        'Use this for discovery — never use Bash to find repos. ' +
        'Returns [{repo_path, last_used}] ordered by most-recent first.',
      inputSchema: {},
    },
    (_args) => {
      logger.debug({ operation: 'recent_repos' }, 'MCP recent_repos invoked');
      const result = handleRecentRepos();
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    },
  );

  // ── default_branch ──────────────────────────────────────────────────────────
  server.registerTool(
    'default_branch',
    {
      description:
        'Return the default branch of a git repo (e.g. "main" or "master") by inspecting ' +
        'refs/remotes/origin/HEAD. Falls back to "main" when the remote is absent or the ' +
        'path is not a git repo. Use instead of running Bash git commands.',
      inputSchema: {
        repo_path: z.string().describe('Absolute path to the git repo'),
      },
    },
    async (args) => {
      logger.debug(
        { operation: 'default_branch', repo_path: args.repo_path },
        'MCP default_branch invoked',
      );
      const result = await handleDefaultBranch(args);
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    },
  );

  // ── search_learnings ────────────────────────────────────────────────────────
  server.registerTool(
    'search_learnings',
    {
      description:
        'Search past agent learnings (shared lane) by trigger/lesson keyword. ' +
        'Cross-repo unless repo is given. ' +
        'Returns lean rows [{trigger, lesson, evidence, repo_path}] — never full learning rows.',
      inputSchema: {
        query: z.string().describe('Keyword to match against trigger/lesson (LIKE search)'),
        repo: z.string().optional().describe('Restrict to this repo_path (default: all repos)'),
      },
    },
    (args) => {
      logger.debug({ operation: 'search_learnings', args }, 'MCP search_learnings invoked');
      const result = handleSearchLearnings(args);
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    },
  );

  // ── Capability-registry tools (list_tasks/get_task/create_task/set_task_status/
  //    close_task/delete_task) ────────────────────────────────────────────────
  // Only registered for an orchestrator-started (conductor) session — same gate
  // as the write tools below, and deliberately NOT for worker sessions.
  //
  // Caller class: 'agent'. Both the conductor and a worker are autonomous
  // Claude Code sessions, not a human at a terminal or the dashboard — exactly
  // CallerClass's 'agent' definition (server/registry/types.ts). Every task.*
  // capability lists 'agent' in its `callers`, so this is the only class that
  // makes sense here.
  //
  // Tier split: the conductor gets every task.* capability; a worker gets only
  // the 'auto' tier — task.list/get. That preserves both boundaries at once.
  // Workers have never had create_task/close_task/delete_task (the write loop
  // below already excluded them) and still don't, because those capabilities
  // are 'ask'/'always-ask'. But workers DO keep the lean list_tasks/get_task
  // read tools they have always had unconditionally, which an all-or-nothing
  // gate on orchestratorWriteEnabled() would have taken away.
  //
  // Filtering on tier rather than on a tool-name allowlist means a new
  // capability lands on the correct side of this boundary by virtue of the
  // tier its author already had to choose — there is no second list to keep
  // in sync, and forgetting to update one cannot silently widen a worker's
  // reach.
  //
  // ONE call, not two: registering the 'auto' tier unconditionally and then
  // the rest for the conductor would register the auto tools twice for the
  // conductor, and the MCP SDK rejects a duplicate tool name.
  //
  // Registering task.create/start/move/close/delete for the conductor does not
  // change its blast radius: those actions already ran immediately with no
  // approval gate via the old COMMANDS write loop (see actions.ts's docblock).
  // This changes the code path — in-process capability handler instead of an
  // RPC to /api/hooks/orchestrator-action — not the "runs immediately"
  // semantics. Adding that approval step is `onGatedInvoke`'s job.
  registerCapabilityMcpTools(server, 'agent', {
    tiers: orchestratorWriteEnabled() ? undefined : ['auto'],
  });

  // ── Write tools (SHR-142) ─────────────────────────────────────────────────
  // Only registered for an orchestrator-started session (base url + token in
  // env). Each RPCs to the main server, which runs the action + reports it.
  // Excludes the four commands the capability registry now generates above
  // (CAPABILITY_MCP_NAMES) so the MCP SDK never sees a duplicate tool name.
  if (orchestratorWriteEnabled()) {
    registerWriteTools(server);
  }

  // ── Worker report_complete (SHR-160) ──────────────────────────────────────
  // Only registered when OCTOMUX_TASK_ID is set (worker mode). The worker calls
  // this tool when it finishes a phase; it RPCs to the phase-complete endpoint.
  if (workerReportEnabled()) {
    registerWorkerTools(server);
  }

  return server;
}

/**
 * Register the conductor write tools. Iterates over COMMANDS (command-registry.ts)
 * and registers every MCP-exposed command (mcp:true) EXCEPT the four now
 * generated by the capability registry above (CAPABILITY_MCP_NAMES) — so today
 * this registers `send_message` and `add_agent`. Each takes structured args
 * (no Bash string) and RPCs to the main server orchestrator-action endpoint. The
 * action executes immediately and an activity update is pushed to the conversation
 * — there is no approval gate.
 *
 * inputSchema uses each command's canonical zod schema (.shape) so the MCP tool
 * accepted fields are always in sync with the executor and the CLI.
 * Any drift is caught by the CLI drift test.
 */
function registerWriteTools(server: McpServer): void {
  const text = (v: unknown) => ({
    content: [{ type: 'text' as const, text: JSON.stringify(v, null, 2) }],
  });

  // Return tool-execution failures as isError results with actionable text
  // (Anthropic tool-design guidance, SHR-163) rather than letting a bare throw
  // surface as an opaque protocol error — the conductor can read and recover.
  const errorResult = (toolName: string, err: unknown) => {
    const message = err instanceof Error ? err.message : String(err);
    logger.warn({ operation: toolName, err: message }, 'MCP write tool failed — returning isError');
    return {
      content: [{ type: 'text' as const, text: `${toolName} failed: ${message}` }],
      isError: true as const,
    };
  };

  for (const cmd of COMMANDS.filter((c) => c.mcp && !CAPABILITY_MCP_NAMES.has(c.name))) {
    // cmd.input is a ZodObject at runtime (all MCP commands use ZodObject schemas).
    // Cast through `z.ZodObject<z.ZodRawShape>` to access `.shape` for the MCP SDK.
    const shape = (cmd.input as z.ZodObject<z.ZodRawShape>).shape;
    server.registerTool(
      cmd.name,
      {
        description: cmd.summary,
        inputSchema: shape,
      },
      async (args: Record<string, unknown>) => {
        try {
          return text(await callOrchestratorAction(cmd.action, args));
        } catch (err) {
          return errorResult(cmd.name, err);
        }
      },
    );
  }
}

/**
 * Register the worker report_complete tool. Only active in worker mode
 * (OCTOMUX_TASK_ID present). The tool RPCs to the main server's
 * POST /api/hooks/phase-complete endpoint authenticated by the worker's hook_token.
 *
 * Distinct from the conductor write tools: conductor writes gate on
 * OCTOMUX_CONVERSATION_ID; worker writes gate on OCTOMUX_TASK_ID.
 */
function registerWorkerTools(server: McpServer): void {
  server.registerTool(
    'report_complete',
    {
      description:
        'Call this when you have finished a phase of your task. ' +
        'phase:implement = the whole task is done. ' +
        'The orchestrator surfaces the right update (spec/plan card, or done + diff link).',
      inputSchema: {
        phase: z.enum(['spec', 'plan', 'implement']).describe('which phase you just completed'),
        summary: z.string().optional().describe('Optional 1–2 sentence summary of what was done'),
        artifacts: z
          .array(z.string())
          .optional()
          .describe('Optional list of artifact file paths produced (e.g. ["spec.md"])'),
      },
    },
    async (args) => {
      const { phase, artifacts } = args;
      logger.info(
        { operation: 'report_complete', phase, task_id: process.env.OCTOMUX_TASK_ID },
        'worker MCP report_complete invoked',
      );

      await callPhaseComplete(phase, artifacts);

      const msg =
        phase === 'implement'
          ? `Phase complete: implement. Task done — the orchestrator will surface the diff.`
          : `Phase complete: ${phase}. The orchestrator will advance to the next phase.`;

      return {
        content: [{ type: 'text' as const, text: msg }],
      };
    },
  );
}

// ─── Entrypoint (launched as --mcp-config subprocess) ────────────────────────

/**
 * Main entrypoint: create the server and connect to stdio transport.
 * Only runs when invoked directly (not when imported as a module).
 */
async function main(): Promise<void> {
  logger.info({ operation: 'startup' }, 'octomux MCP server starting (stdio)');

  const server = createOctomuxMcpServer();
  const transport = new StdioServerTransport();

  await server.connect(transport);

  logger.info({ operation: 'startup' }, 'octomux MCP server connected to stdio');
}

// Run main ONLY when executed directly (claude spawns this as an --mcp-config
// stdio subprocess). Guard against module import (e.g. the build bundling it as
// an entry, or a test importing createOctomuxMcpServer) auto-spawning a server.
function isMainModule(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return fileURLToPath(import.meta.url) === entry;
  } catch {
    return false;
  }
}

if (isMainModule()) {
  main().catch((err) => {
    // Use stderr to avoid corrupting the stdio MCP protocol stream
    process.stderr.write(`octomux MCP server fatal error: ${err}\n`);
    process.exit(1);
  });
}
