/** Thin facade — poll loops live in ./poller/*. */
export {
  startPolling,
  stopPolling,
  checkTaskStatus,
  pollStatuses,
  pollTerminalActivity,
  ensureHooksInstalled,
  detectPR,
  pollPRs,
  checkMergedPRs,
  pollMergedPRs,
  pollReviewerRequests,
  sweepStuckReviewRuns,
  pollSoftDeletes,
  attachDeepReviewAgent,
  pollWalkthroughHandoffs,
  pollPRsAndReviewers,
  repoNameWithOwner,
  parseNameWithOwner,
} from './poller/index.js';
